# Generated by Django 4.0.4 on 2022-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_password',
            field=models.CharField(default='Das5ahec', max_length=255, verbose_name='mail_password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
    ]
