# Generated by Django 4.0.4 on 2022-05-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_email_password_alter_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
